### ISSUE TITLE
Alias not supported on update method

### ISSUE THREAD

**Issue by rmarinchev** [heminei/php-query-builder#2]
As a user, I would like to be able to build an **update** statement with a **join**. 

An example SQL query:
```SQL
UPDATE table AS t
INNER JOIN another_table AS at ON t.id = at.tableID
SET t.isActive = 1
WHERE at.isActive = 1
```

ideally should be built using

```PHP
$query = new Query();
$query->update('table', 't')
->innerJoin('another_table', 'at', 't.id=at.tableID')
->set('t.isActive=:isActive')->setVar('isActive', 1)
->andWhere('at.isActive', 1)
```

In addition, It would be great if we can bind values directly like this
```PHP
->set('t.isActive', 1)
```
instead of this
```PHP
->set('t.isActive=:isActive')->setVar('isActive', 1)
```

**Comment by heminei** [comment]
The bug is fixed in the new version: [1.2.2](https://github.com/heminei/php-query-builder/releases/tag/1.2.2) 
Thanks :)
