### ISSUE TITLE
where condition generates some kind of id

### ISSUE THREAD

**Issue by ghost** [heminei/php-query-builder#3]
I'm using this code to add a where condition:
```php
$query->where('users.id', 10);
```
And the output is:
```sql
WHERE users.id=:6e95496c414eb3756a2a19646b70c8fe830d3d28
```
Each time I run this code the string is different, for example:
```sql
WHERE users.id=:2060e4f5268a8401be042e403b36cb4cc0034f11
```

This makes the entire library pretty much unusable.

**Comment by heminei** [comment]
The query builder use bind parameters. The hash is a unique parameter name. Method "getQueryString" is for debugging only. What do you want to do?

**Comment by ghost** [comment]
Ah, I didn't know `getQueryString` was for debugging only. What is the correct method for getting the raw SQL string?

**Comment by heminei** [comment]
You can't get real SQL with the PDO driver. You can get similar query with "getQueryString(true)" but only for debugging. If you want to fetch data use [https://github.com/heminei/php-query-builder#fetching-data](this methods)

**Comment by ghost** [comment]
Ah okay thank you!
